services:
  - type: web
    name: app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: worker2
    name: background-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python consumer2.py
  
  - type: worker3
    name: background-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python consumer3.py